sudo: false
language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
before-install:
  - composer self-update
install:
  - gem install sass
  - npm install
  - composer --prefer-source --dev install
script:
  - gulp bower
  - gulp
  - vendor/bin/phpspec run
  - vendor/bin/phpunit -c app/phpunit.xml